class Abjuration {
  static List<String> list = [
    "Aid",
    "Alarm",
    "Antilife Shell",
    "Antimagic Field",
    "Arcane Lock",
    "Armor of Agathys",
    "Aura of Life",
    "Aura of Purity",
    "Banishing Smite",
    "Banishment",
    "Beacon of Hope",
    "Blade Ward",
    "Circle of Power",
    "Counterspell",
    "Death Ward",
    "Dispel Evil and Good",
    "Dispel Magic",
    "Forbiddance",
    "Freedom of Movement",
    "Globe of Invulnerability",
    "Glyph of Warding",
    "Greater Restoration",
    "Guards and Wards",
    "Holy Aura",
    "Imprisonment",
    "Lesser Restoration",
    "Mage Armor",
    "Magic Circle",
    "Mind Blank",
    "Mordenkainen's Private Sanctum",
    "Nondetection",
    "Pass without Trace",
    "Planar Binding",
    "Prismatic Wall",
    "Protection from Energy",
    "Protection from Evil and Good",
    "Protection from Poison",
    "Remove Curse",
    "Resistance",
    "Sanctuary",
    "Shield",
    "Shield of Faith",
    "Stoneskin",
    "Symbol",
    "Warding Bond",
  ];
}

class Conjuration {
  static List<String> list = [
    "Acid Splash",
    "Arcane Gate",
    "Arms of Hadar",
    "Call Lightning",
    "Cloud of Daggers",
    "Cloudkill",
    "Conjure Animals",
    "	Conjure Barrage",
    "Conjure Celestial",
    "Conjure Elemental",
    "Conjure Fey",
    "Conjure Minor Elementals",
    "Conjure Volley",
    "Conjure Woodland Beings",
    "Create Food and Water",
    "Demiplane",
    "Dimension Door",
    "Drawmij's Instant Summons",
    "Ensnaring Strike",
    "Entangle",
    "Evard's Black Tentacles",
    "Find Familiar",
    "Find Steed",
    "Flaming Sphere",
    "Fog Cloud",
    "Gate",
    "Grasping Vine",
    "Grease",
    "Guardian of Faith",
    "Hail of Thorns",
    "Heroes' Feast",
    "Hunger of Hadar",
    "Incendiary Cloud",
    "Insect Plague",
    "Leomund's Secret Chest",
    "Mage Hand",
    "Maze",
    "Misty Step",
    "Mordenkainen's Faithful Hound",
    "Mordenkainen's Magnificent Mansion	",
    "Planar Ally",
    "Plane Shift",
    "Poison Spray",
    "Produce Flame",
    "Sleet Storm",
    "Spirit Guardians",
    "Stinking Cloud",
    "Storm of Vengeance",
    "Teleport",
    "Teleportation Circle",
    "Tenser's Floating Disk",
    "Transport via Plants",
    "Tree Stride",
    "Tsunami",
    "Unseen Servant",
    "Wall of Thorns",
    "Web",
    "Wish",
    "Word of Recall",
  ];
}

class Divination {
  static List<String> list = [
    "Arcane Eye",
    "Augury",
    "Beast Sense",
    "Clairvoyance",
    "Commune",
    "Commune with Nature",
    "Comprehend Languages",
    "Contact Other Plane",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "Detect Thoughts",
    "Divination",
    "Find the Path",
    "Find Traps",
    "Foresight",
    "Guidance",
    "Hunter's Mark",
    "Identify",
    "Legend Lore",
    "Locate Animals or Plants",
    "Locate Creature",
    "Locate Object",
    "Rary's Telepathic Bond",
    "Scrying",
    "See Invisibility",
    "Speak with Animals",
    "Tongues",
    "True Seeing",
    "True Strike",
  ];
}

class Enchantment {
  static List<String> list = [
    "Animal Friendship",
    "Animal Messenger",
    "Antipathy/Sympathy",
    "Bane",
    "Bless",
    "Calm Emotions",
    "Charm Person",
    "Command",
    "Compelled Duel",
    "Compulsion",
    "Confusion",
    "Crown of Madness",
    "Dissonant Whispers",
    "Dominate Beast",
    "Dominate Monster",
    "Dominate Person",
    "Enthrall",
    "Feeblemind",
    "Friends",
    "Geas",
    "Heroism",
    "Hex",
    "Hold Monster",
    "Hold Person",
    "Mass Suggestion",
    "Modify Memory",
    "Otto's Irresistible Dance",
    "Power Word Kill",
    "Power Word Stun",
    "Sleep",
    "Suggestion",
    "Tasha's Hideous Laughter",
    "Vicious Mockery",
    "Zone of Truth",
  ];
}

class Evocation {
  static List<String> list = [
    "Aura of Vitality",
    "Bigby's Hand",
    "Blade Barrier",
    "Blinding Smite",
    "Branding Smite",
    "Burning Hands",
    "Chain Lightning",
    "Chromatic Orb",
    "Cone of Cold",
    "Contingency",
    "Continual Flame",
    "Crusader's Mantle",
    "Cure Wounds",
    "Dancing Lights",
    "Darkness",
    "Daylight",
    "Delayed Blast Fireball",
    "Destructive Wave",
    "Divine Favor",
    "Divine Word",
    "Earthquake",
    "Eldritch Blast",
    "Faerie Fire",
    "Fire Bolt",
    "Fire Shield",
    "Fire Storm",
    "Fireball",
    "Flame Blade",
    "Flame Strike",
    "Forcecage",
    "Guiding Bolt",
    "Gust of Wind",
    "Hallow",
    "Heal",
    "Healing Word",
    "Hellish Rebuke",
    "Ice Storm",
    "Leomund's Tiny Hut",
    "Light",
    "Lightning Bolt",
    "Magic Missile",
    "Mass Cure Wounds",
    "Mass Heal",
    "Mass Healing Word",
    "Melf's Acid Arrow",
    "Meteor Swarm",
    "Moonbeam",
    "Mordenkainen's Sword",
    "Otiluke's Freezing Sphere",
    "Otiluke's Resilient Sphere",
    "Power Word Heal",
    "Prayer of Healing",
    "Prismatic Spray",
    "Ray of Frost",
    "Sacred Flame",
    "Scorching Ray",
    "Searing Smite",
    "Sending",
    "Shatter",
    "Shocking Grasp",
    "Spiritual Weapon",
    "Staggering Smite",
    "Sunbeam",
    "Sunburst",
    "Telepathy",
    "Thunderous Smite",
    "Thunderwave",
    "Wall of Fire",
    "Wall of Force",
    "Wall of Ice",
    "Wall of Stone",
    "Wind Wall",
    "Witch Bolt",
    "Wrathful Smite",
  ];
}

class Necromancy {
  static List<String> list = [
    "Animate Dead",
    "Astral Projection",
    "Bestow Curse",
    "Blight",
    "Blindness/Deafness",
    "Chill Touch",
    "Circle of Death",
    "Clone",
    "Contagion",
    "Create Undead",
    "Eyebite",
    "False Life",
    "Feign Death",
    "Finger of Death",
    "Gentle Repose",
    "Harm",
    "Inflict Wounds",
    "Magic Jar",
    "Raise Dead",
    "Ray of Enfeeblement",
    "Ray of Sickness",
    "Resurrection",
    "Revivify",
    "Spare the Dying",
    "Speak with Dead",
    "True Resurrection",
    "Vampiric Touch",
  ];
}

class Transmutation {
  static List<String> list = [
    "Wind Walk",
    "Water Walk",
    "Water Breathing",
    "True Polymorph",
    "Time Stop",
    "Thorn Whip",
    "Thaumaturgy",
    "Telekinesis",
    "Swift Quiver",
    "Stone Shape",
    "Spike Growth",
    "Spider Climb",
    "Speak with Plants",
    "Slow",
    "Shillelagh",
    "Shapechange",
    "Sequester",
    "Rope Trick",
    "Reverse Gravity",
    "Reincarnate",
    "Regenerate",
    "Purify Food and Drink",
    "Prestidigitation",
    "Polymorph",
    "Plant Growth",
    "Passwall",
    "Move Earth",
    "Message",
    "Mending",
    "Meld into Stone",
    "Magic Weapon",
    "Longstrider",
    "Lightning Arrow",
    "Levitate",
    "Knock",
    "Jump",
    "Heat Metal",
    "Haste",
    "Goodberry",
    "Glibness",
    "Giant Insect",
    "Gaseous Form",
    "Fly",
    "Flesh to Stone",
    "Feather Fall",
    "Fabricate",
    "Expeditious Retreat",
    "Etherealness",
    "Enlarge/Reduce",
    "Enhance Ability",
    "Elemental Weapon",
    "Druidcraft",
    "Disintegrate",
    "Darkvision",
    "Create or Destroy Water",
    "Cordon of Arrows",
    "Control Weather",
    "Control Water",
    "Blink",
    "Barkskin",
    "Awaken",
    "Animate Objects",
    "Animal Shapes",
    "Alter Self",
  ];
}

class Ilusion {
  static List<String> list = [
    "Weird",
    "Simulacrum",
    "Silent Image",
    "Silence",
    "Seeming",
    "Project Image",
    "Programmed Illusion",
    "Phantom Steed",
    "Phantasmal Killer",
    "Phantasmal Force",
    "Nystul's Magic Aura",
    "Mislead",
    "Mirror Image",
    "Mirage Arcane",
    "Minor Illusion",
    "Major Image",
    "Magic Mouth",
    "Invisibility",
    "Illusory Script",
    "Hypnotic Pattern",
    "Hallucinatory Terrain",
    "Greater Invisibility",
    "Fear",
    "Dream",
    "Disguise Self",
    "Creation",
    "Color Spray",
    "Blur",
  ];
  static Map<String, String> map = {
    "Blur" : "Nublar",
    "Color Spray" : "Leque Cromático",
    "Creation" : "Criação",
    "Disguise Self" : "Disfarçar",
    "Dream" : "Sonho",
    "Fear" : "Medo",
    "Greater Invisibility" : "Invisibilidade Maior",
    "Hallucinatory Terrain" : "Terreno Alucinógeno",
    "Hypnotic Pattern" : "Padrão Hipnótico",
    "Illusory Script" : "Escrita Ilusória",
    "Invisibility" : "Invisibilidade",
    "Magic Mouth" : "Boca Encantada",
    "Major Image" : "Imagem Maior",
    "Minor Illusion" : "Ilusão Menor",
    "Mirage Arcane" : "Miragem",
    "Mirror Image" : "Reflexos",
    "Mislead" : "Despistar",
    "Nystul's Magic Aura" : "Aura Mágica de Nystul",
    "Phantasmal Force" : "Força Fantasmagórica",
    "Phantasmal Killer" : "Assasino Fantasmagórico",
    "Phantom Steed" : "Montaria Fantasmagórica",
    "Programmed Illusion" : "Ilusão Programada",
    "Project Image" : "Projetar Imagem",
    "Seeming" : "Similaridade",
    "Silence" : "Silêncio",
    "Silent Image" : "Imagem Silenciosa",
    "Simulacrum" : "Simulacro",
    "Weird" : "Encarnação Fantasmagórica",
  };
}